### ISSUE TITLE
Update index and 404 here

### ISSUE THREAD

**Issue by DrDaveD** [hpcng/singularity-web-lbl#1]
This repository serves https://singularity.lbl.gov, the first home page for singularity.  As requested in apptainer/singularity-userdocs#408 and discussed in today's Apptainer community call, please update the index.html here to forward to https://apptainer.org instead of https://singularity.hpcng.org, and make a 404 message that says the page is not found but gives people a choice to forward to the new Apptainer documentation at https://apptainer.org/docs (without a sub-URL) or the archive of the old documentation with the same sub-URL under https://singularityware.github.io.

@brianclemens @gmkurtzer @vsoch

**Comment by DrDaveD** [comment]
@vsoch, #2 which is now merged does the equivalent of what was requested here.  I googled for some old links and they seem to work right to me.  Does it look good to you?

**Comment by vsoch** [comment]
This is a great start!

I think it should be an equal playing field - e.g., right now I see:

https://singularityware.github.io/install-linux

![image](https://user-images.githubusercontent.com/814322/175796667-18386dcc-b5d6-45fc-9b5b-7122bf0744de.png)

And since this was the start for both projects, the right thing to do is to say `Documentation for Apptainer is hosted at <> and for Sylabs Singularity is  at <>` as it could be misleading the user that Apptainer is the one child of the project.

**Comment by vsoch** [comment]
The most important thing is for the user to find what they are looking for, and coming here from an old link, often users don't have a choice about which is installed on their resource, so we want them to arrive at these old pages and have a clear path forward either way!

**Comment by DrDaveD** [comment]
I don't think that's necessary.  I doubt there's much traffic left at the old site anyway.

**Comment by vsoch** [comment]
I do. Should we ask the larger community, or just do the right thing without that?

**Comment by vsoch** [comment]
heyo! Any updates? Any way I can help?

**Comment by DrDaveD** [comment]
It's fine the way it is.

**Comment by reidpr** [comment]
@DrDaveD, not cool to ask for V’s feedback and then completely blow it it off.

Personally I think she’s right that it should point to both forks, for the reasons she cites. If you disagree, can you please give actual reasoning?

**Comment by rowlandm** [comment]
I didn't even know there were two child projects. Choosing an open and transparent in this situation would be quite helpful to anyone looking at this documentation.

**Comment by gmkurtzer** [comment]
If I recall correctly, the initial request was to provide users landing on legacy pages a pathway to get to current documentation. I believe this fixes that.

To acknowledge some of the comments in the thread, there is only one truly community Singularity project which is now hosted by the Linux Foundation. The project has been renamed to Apptainer to alleviate brand confusion.

So, as it pertains to the documentation links, I agreed with @DrDaveD and support keeping all links and interests first and foremost in the open community.

**Comment by vsoch** [comment]
Thanks for your comment in the discussion @gmkurtzer! "Current" documentation could mean either Apptainer or Singularity, depending on what the user is looking for. Many would see it as lacking transparency to say that there is only one project, and disagree with you about Apptainer being "the" Singularity, at least based on folks that I've talked to. This isn't about the historical squabbles between projects, it's about transparency and helping the user that stumbles onto the old page. The original documentation for the parent project has grown into both projects. Can we not be supportive of one another, and for cases like this clearly communicate that both projects exist? If it's such a small set of links as @DrDaveD has said, why is there such fight against this?

@ArangoGutierrez you just attended ISC, and the containers meeting? Can you comment on community sentiment about whether the two child projects of the original Singularity project are both valuable and whether this group would value this transparency? I would like to see it, and I think it's the right thing to do.

**Comment by gmkurtzer** [comment]
The project lineage is crystal clear...

I founded, created, named, built the vision, and led the project from its inception at LBL/DOE/UCOP until I gave it to the Linux Foundation.  This is not debatable, it is fact.

There have been lots of amazing contributions (including yourself, the Sylabs team, and many others) but to point out simple fact, I've always led the official project. Maybe I didn't do everything perfect, but I tried my best and I don't think the project or community deserved to be forked. It would have been nice to know beforehand if I could have been doing better, or fixing something, but nothing was ever brought up. As far as I know, the fork was a complete surprise to everyone outside of Sylabs.

Forking an open source project, without clear, compelling, and ample reasons why the fork was absolutely necessary is ALWAYS bad for the community. But when a project is forked into a commercial agenda, without clear public reasoning and under the same name and branding, it is stealing.

But, we are trying to do the right thing. Instead of fighting over the name and branding, we decided to rename the official project when it was moved it into the Linux Foundation. As a result, it doesn't surprise me that people aren't very familiar with Apptainer yet, but we are going to continue to drive the vision that I set out back in 2016 and always work in the best interest in the community.

This is why I moved the project into the Linux Foundation and it is why the links will continue to point to http://www.apptainer.org.

Warmest regards,
Greg

**Comment by vsoch** [comment]
This isn’t about the lineage. It’s about putting the user first and acting to respond to their needs. A user that stumbles on these old docs could be looking for either project, and often that decision is out of their control and up to the underlying institution that has made the choice for them. To best serve the Singularity user here we need to provide transparent access to both projects for them to consume.

**Comment by gmkurtzer** [comment]
I am absolutely putting the users and the open source project and community first.

It's okay if you don't agree, but I'm not going to debate opinion. 

Take care.

**Comment by rowlandm** [comment]
> I didn't even know there were two child projects. Choosing an open and transparent in this situation would be quite helpful to anyone looking at this documentation.

As someone who advocates for users and sysadmins of Singularity, I would like to re-iterate the fact that showing the two child project documentations would be pretty handy.

Take care.

**Comment by gmkurtzer** [comment]
@rowlandm I am truly sorry to disappoint you but my morals and ethics are strong when it comes to doing the right thing by the community.

If Sylabs on the other hand wishes to explain their reasoning for why they forked, why they kept the same name, and now that the project is in the Linux Foundation, would they be interested in being a single community again, then with compelling community first justification of their actions, I would be happy to reconsider my assessment.

**Comment by DrDaveD** [comment]
> @DrDaveD, not cool to ask for V’s feedback and then completely blow it it off.
> 
> Personally I think she’s right that it should point to both forks, for the reasons she cites. If you disagree, can you please give actual reasoning?

@reidpr  I was just asking for feedback on her original request.  I went through considerable effort to satisfy that request, finally recruiting one of my contacts with know-how to fulfill it.  Vanessa's response was asking for more and I disagreed with that additional request.  It's all of such little relevance anyway because I doubt hardly anybody looks at that ancient website which has been obsolete for many years.  It's not worth making a fuss about it or spending any more time on it.

I think it would be nice if someone would be willing to take the time and effort to explain the two projects in Wikipedia where many people would see it, but so far it hasn't been a priority for anyone.

Vanessa and I have been the two community members doing the most to try to help bridge the two projects and keep them cooperating.  She and I just happen to disagree on this minor item.  It's time to let it go.

**Comment by ArangoGutierrez** [comment]
> @DrDaveD, not cool to ask for V’s feedback and then completely blow it it off.
> 
> Personally I think she’s right that it should point to both forks, for the reasons she cites. If you disagree, can you please give actual reasoning?

Same, I think the community deserves to be treated properly and know the current state of given project. pointing at both is the right thing to do.

**Comment by vsoch** [comment]
> I think it would be nice if someone would be willing to take the time and effort to explain the two projects in Wikipedia where many people would see it, but so far it hasn't been a priority for anyone.

@DrDaveD I would be happy to help with this! I was the first to write the Singularity page in Wikipedia but it was rejected (later rewritten by new staff at Sylabs I think?) so likely the ultimate poster should probably be a guy, because I don’t have much luck on Wikipedia. 😆 

Perhaps a few folks that have lived through the 2018-2022 story (when I was not a part of Sylabs / RStor / HPCng etc) could send me a small description of events, and I’ll put them together into a shared Google Doc for all of us to review? However I want to set a few rules:

- the document is focused on events that are factual, and straight forward, as in have a public reference (this is generally required by Wikipedia). 
- no blaming, calling out of any individuals or entities and putting them into a negative light.
- A clear tone that is positive and communicated a supportive environment moving forward.
- No personal biases or opinions about the events.

We are writing this to have a professional, and positive tone, and I will work to put pieces together and weave into a consolidated, straightforward story that can educate the reader and provide some starting point to think about distinguishing the now separate projects, and then we can provide links to each. I know several people have written accounts in different places, although not all of them conform to the rules above so they might need some tweaking. Then when we have a version we like, it can be copy pasted to Wikipedia. How does that sound?

**Comment by ArangoGutierrez** [comment]
++ to @vsoch idea.
can we re-open this issue as well

**Comment by gmkurtzer** [comment]
I don’t know what happens at Wikipedia, but in my experience being a guy doesn’t help. None of my edits or contributions have ever been accepted and I gave up many years ago.

In terms of an overview, as I said, I founded, created, named, built the vision, and led the project from its inception at LBL/DOE/UCOP until I gave it to the Linux Foundation. Sylabs forked it and took the name. If you want to sugar coat it, be my guest, but that is 100% factual and concise.

If you want the details about what happened with Sylabs, sorry, I’m under legal obligation not to share but certainly you can imagine in what world a CEO/founder of their own company would no longer be there, especially considering the company hasn’t changed strategy, products, or vision from what I created; the only thing that has changed is the ownership.

There are lots of public documents and records that clearly show that I created Sylabs. Personally, I’ll share that I made a huge mistake of bringing Singularity as an open source project under Sylabs. I believe that is the cause of why many open source contributors were pushed out as more and more strategy and development was occurring behind locked doors. It also created a considerable amount of bad feelings between inside Sylabs and the community, that I was always trying to manage. 

The most important question for a Wikipedia article about two versions of Singularity is why did Sylabs fork the project and retain the name. There has been NO compelling reasons, feedback, or open community discussions about this that has ever happened in the public. The only thing I’ve seen is a vague series of comments that it was for the benefit of the community but has no specifics. This is the absolute crux of the issue. Everyone deserves to know, why are there two Singularity projects and how bisecting the community was somehow the best for the community.

If you want to post something to Wikipedia about two projects existing, this is the main critical point and ironically it can only be gotten from Sylabs. Without it, the Sylabs version will always be seen as a corporate power grab.

**Comment by DrDaveD** [comment]
I'm not sure a google doc will be helpful because of the translation formats.   This isn't a very good place for the discussion.  I suggest that we use a #wikipedia channel on the apptainer slack and discuss there.  Does that sound ok to you @vsoch?

Meanwhile, I had some success with updating the [Singularity_(software)](https://en.wikipedia.org/wiki/Singularity_(software)) wikipedia page, including adding a couple paragraphs to the end of the History section about the two projects including links to two so far nonexistent pages for the two projects.

**Comment by vsoch** [comment]
There is actual, studied gender inequality on WIkipedia!

> Wikipedia has rapidly become an invaluable destination for millions of information-seeking users. However, media reports suggest an important challenge: only a small fraction of Wikipedia’s legion of volunteer editors are female. In the current work, we present a scientific exploration of the gender imbalance in the English Wikipedia’s population of editors. We look at the nature of the imbalance itself, its effects on the quality of the encyclopedia, and several conflict-related factors that may be contributing to the gender gap. Our findings confirm the presence of a large gender gap among editors and a corresponding gender-oriented disparity in the content of Wikipedia’s articles. Further, we find evidence hinting at a culture that may be resistant to female participation.

:point_right:  https://dl.acm.org/doi/pdf/10.1145/2038558.2038560. 

Wikipedia has a fairly strict conflict of interest policy https://en.wikipedia.org/wiki/Wikipedia:Conflict_of_interest and personally knowing people in the project I thus have one. But I think I can help to lead a community initiative to work on the separate pages - and my suggestion for both projects is to wait maybe a year for each to get a little more firmly footed in uniqueness, and then there can be community efforts to write nice pages for each! I've added a note to my calendar for next year (and chat with @DrDaveD on slack) and will ping when this time comes. 

And I have no control over this specific issue, but I hope y'all can heal and find ways to support one another. Details like this are important, and understanding that we must be transparent and (moving forward) put the past behind us, and put the needs of the larger Singularity community first, which is strong on both sides. Thanks for the discussion in this issue, and especially you @DrDaveD for engaging in a positive way, with focus on moving forward and working together.

**Comment by DrDaveD** [comment]
Thanks for the link to the Conflict of Interest, I wasn't aware of it.  It looks like it's OK if you disclose it on the Talk page, so I went ahead and did that on the Singularity_(software) and Apptainer Talk pages.  I think there often has to be a conflict of interest by their definition, because otherwise people won't know the facts or won't care.

I don't understand the reasoning on waiting a year, but if you want to wait on the SingularityCE page that's up to you.

**Comment by vsoch** [comment]
> I don't understand the reasoning on waiting a year, but if you want to wait on the SingularityCE page that's up to you.

It will give some time for healing, and for the projects to get better established on their individual roadmaps. I think you did a great job on the current page and we can do the same on the subpages, but not right now when it's a bit heated, and when the projects are still fairly connected.

**Comment by DrDaveD** [comment]
It's important for Apptainer to get its name onto Wikipedia, so that page is already created.  There's a link on the Singularity_(software) page to the Sylabs home page so people can find out more info about SingularityCE that way.  If it's going to be a long time, for now I'll change the SingularityCE mentions into references to the Sylabs SingularityCE web page instead of to a non-existent Wikipedia page.
